BookPakistanTour/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BookPakistanTour.Models
{
    public class LoginViewModel
    {
        [Display(Name = "Email")]
        [Required(ErrorMessage = "The Email field is Required")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*",
            ErrorMessage = "Email Not Verified !!")]
        public string Email { get; set; }


        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Required]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Password Is Too Short..!!")]
        public string Password { get; set; }


        [Display(Name = "RememberMe")]
        public bool RememberMe { get; set; }




    }
}

BookPakistanTour/Controllers/RecoveryEmailController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using BookPakistanTour.Models;
using BookPakistanTourClasslibrary.UserManagement;

namespace BookPakistanTour.Controllers
{
    public class RecoveryEmailController : Controller
    {
        // GET: RecoveryEmail
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.HideSlider = true;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(recoveryEmail data)
        {
            if (ModelState.IsValid)
            {
                User user = new UserHandler().GetUserByEmail(data.Email);
                if (user == null)
                {
                    ViewBag.error = "Email Not Registered. Please Enter Registered Email Address";
                    return View();
                }

                try
                {
                    string randomnumb = Path.GetRandomFileName().Replace(".", "");
                    var message = new MailMessage { From = new MailAddress("ADD_YOUR_OWN") };
                    message.To.Add(data.Email);
                    message.Subject = "-No-Reply- Password Recovery Email by PAKISTAN TOURISM";
                    message.IsBodyHtml = true;
                    message.Body = "Please use this password: <b><u>" + randomnumb +
                                   "</u></b> , Next Time You Login! And dont forget to change your password";

                    SmtpClient smtp = new SmtpClient
                    {
                        Host = "smtp.gmail.com",
                        Port = 587,
                        Credentials = new System.Net.NetworkCredential
                            ("ADD_YOUR_OWN", "ADD_YOUR_OWN"),
                        EnableSsl = true
                    };



                    smtp.Send(message);
                    user.Password = randomnumb;
                    new UserHandler().UpdateUser(user);
                    ViewBag.success = "Email Has been sent to  " + data.Email;

                    ViewBag.HideSlider = true;
                    return View();
                }
                catch (Exception)
                {
                    ViewBag.error = "Error Sending Mail. Please Try Again Later!";
                    ViewBag.HideSlider = true;
                    return View();
                }
            }
            return View();
        }
    }
}

BookPakistanTour/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using BookPakistanTour.Models;
using BookPakistanTourClasslibrary;
using BookPakistanTourClasslibrary.LocationManagement;
using BookPakistanTourClasslibrary.UserManagement;
using FYProject1.Models;

namespace BookPakistanTour.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Login()
        {

            HttpCookie myCookie = Request.Cookies["idpas"];
            if (myCookie != null)
            {
                User u = new UserHandler().GetUser(myCookie.Values["lid"], myCookie.Values["psd"]);

                if (u != null)
                {
                    myCookie.Expires = DateTime.Today.AddDays(7);
                    Response.SetCookie(myCookie);

                    Session.Add(WebUtil.CURRENT_USER, u);

                    if (u.IsInRole(WebUtil.ADMIN_ROLE))
                    {
                        return RedirectToAction("AdminPanel", "Admin");
                    }

                    return RedirectToAction("Index", "Home");
                }
            }

            ViewBag.Controller = Request.QueryString["ctl"];
            ViewBag.Action = Request.QueryString["act"];
            ViewBag.HideSlider = true;
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel data)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.HideSlider = true;
                return View();
            }

            User u = new UserHandler().GetUser(data.Email, data.Password);

            if (u != null)
            {
                if (data.RememberMe)
                {
                    HttpCookie c = new HttpCookie("idpas")
                    {
                        Expires = DateTime.Today.AddDays(7),
                    };
                    c.Values.Add("lid", u.Email);
                    c.Values.Add("psd", u.Password);
                    Response.SetCookie(c);
                }

                Session.Add(WebUtil.CURRENT_USER, u);

                if (u.IsInRole(WebUtil.ADMIN_ROLE))
                {
                    return RedirectToAction("AdminPanel", "Admin");
                }
                else
                {
                    try
                    {
                        var message = new MailMessage { From = new MailAddress(u.Email) };
                        message.To.Add("ADD_YOUR_OWN");
                        message.Subject = "User Login From Email: " + message.From;
                        message.IsBodyHtml = true;
                        message.Body = "A user Just Log In to Your Site  <br/><br/> Name: " + u.FullName + " <br/> Email: " + u.Email;

                        SmtpClient smtp = new SmtpClient
                        {
                            Host = "smtp.gmail.com",
                            Port = 587,
                            Credentials = new System.Net.NetworkCredential
                                ("ADD_YOUR_OWN", "ADD_YOUR_OWN"),
                            EnableSsl = true
                        };
                        smtp.Send(message);
                        return RedirectToAction("Index", "Home");
                    }
                    catch (Exception)
                    {
                        ViewBag.failed = "You are Required to have an Internet Connection to Login.";
                    }
                }
            }
            else
            {
                ViewBag.failed = "Invalid Username or Password! Please Try Again ";
            }
            ViewBag.HideSlider = true;
            return View();
        }

        public ActionResult Logout()
        {
            ActionResult obj;

            User u = (User)Session[WebUtil.CURRENT_USER];

            if (u != null && u.IsInRole(WebUtil.ADMIN_ROLE))
            {
                obj = RedirectToAction("Login", "User");
            }
            else
            {
                obj = RedirectToAction("Index", "Home");
            }

            Session.Abandon();

            HttpCookie ck = Request.Cookies["idpas"];
            if (ck != null)
            {
                ck.Expires = DateTime.Now;
                Response.SetCookie(ck);
            }
            return obj;
        }

        [HttpGet]
        public ActionResult SignUp()
        {
            ViewBag.HideSlider = true;
            LocationHandler lh = new LocationHandler();
            ViewBag.CountryList = ModelHelper.ToSelectItemList(lh.GetCountries());

            return View();
        }

        [HttpPost]
        public ActionResult SignUp(FormCollection fdata)
        {
            try
            {
                User u = new User
                {
                    FullName = fdata["FullName"],
                    Email = fdata["Email"],
                    Password = fdata["Password"],
                    FullAddress = fdata["FullAddress"],
                    Phone = Convert.ToInt64(fdata["Phone"]),
                    IsActive = false,
                    City = new City { Id = Convert.ToInt32(fdata["CityList"]) },
                    BirthDate = fdata["BirthDate"]
                };

                string gender = Convert.ToString(fdata["Gender"]);
                if (gender != null && gender == "Male")
                {
                    u.Male = true;
                    u.Female = false;
                }
                else if (gender != null && gender == "Female")
                {
                    u.Male = false;
                    u.Female = true;
                }

                u.Role = new UserHandler().GetRoleById(2);

                long numb = DateTime.Now.Ticks;
                int count = 0;
                foreach (string fname in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[fname];
                    if (!string.IsNullOrEmpty(file?.FileName))
                    {
                        string url = "/ImagesData/UserImages/" + numb + "_" + ++count + file.FileName.Substring(file.FileName.LastIndexOf(".", StringComparison.Ordinal));
                        string path = Request.MapPath(url);
                        file.SaveAs(path);
                        u.ImageUrl = url;
                    }
                    else
                    {
                        string url = "/ImagesData/UserImages/noimage.jpg";
                        u.ImageUrl = url;
                    }
                }

                new UserHandler().Adduser(u);
                ViewBag.HideSlider = true;
                return RedirectToAction("Login");

            }
            catch (Exception)
            {
                throw;
            }


        }

        [HttpGet]
        public ActionResult CityLists(int id)
        {
            DDViewModel dm = new DDViewModel
            {
                Name = "CityList",
                Label = "- Your City -",
                Values = ModelHelper.ToSelectItemList(new LocationHandler().GetCities(new Country { Id = id }))
            };

            return PartialView("~/Views/Shared/_DDLView.cshtml", dm);
        }

        [HttpGet]
        public ActionResult UserManagment()
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Home", act = "Index" });
            }

            List<User> users = new UserHandler().GetAllUsers();

            ViewBag.roles = ModelHelper.ToSelectItemList(new UserHandler().GetRoles());
            ViewBag.message = TempData["message"];
            return View(users);
        }

        [HttpGet]
        public ActionResult UserDetails(int? id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Home", act = "Index" });
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = new UserHandler().GetUserById(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        public ActionResult UserGuestUpdate(int? id)
        {
            LocationHandler lh = new LocationHandler();
            ViewBag.CountryList = ModelHelper.ToSelectItemList(lh.GetCountries());

            User u = (User)Session[WebUtil.CURRENT_USER];
            if (u != null && u.IsInRole(WebUtil.ADMIN_ROLE))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                return RedirectToAction("UserEdit", new { id = u.Id });
            }
            else if (u != null && !(u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                User user = new UserHandler().GetUserById(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                ViewBag.HideSlider = true;
                return View(user);
            }
            ViewBag.HideSlider = true;
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult UserGuestUpdate(User user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    new UserHandler().UpdateUser(user);

BookPakistanTour/Views/User/Login.cshtml
@model BookPakistanTour.Models.LoginViewModel

@{
    ViewBag.Title = "Login";
}

<div class="col-lg-9">
    <div class="login-box">

        @if (ViewBag.failed != null)
        {
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <i class="fa fa-exclamation-circle"></i><strong> ERROR!</strong> @ViewBag.failed <a href="@Url.Action("SignUp")">Register</a>
            </div>
        }

        <h2>Login</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RememberMe, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.RememberMe)
                            @Html.ValidationMessageFor(model => model.RememberMe, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Login" class="btn btn-default" />
                    </div>
                </div>

                <div style="font-size: small; margin-top: 5px">
                    <a href="@Url.Action("Index", "RecoveryEmail")">Forgot Your Password? </a>
                    <a class="pull-right" href="@Url.Action("SignUp", "User")">REGISTER HERE! </a>
                </div>
                <div style="font-size: small; margin-top: 5px" class="pull-right">

                </div>
            </div>
        }
    </div>
</div>

BookPakistanTour/Views/User/SignUp.cshtml
@model BookPakistanTourClasslibrary.UserManagement.User

@{
    ViewBag.Title = "SignUp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-9 login-box">

    <h2 class="text-center">User Registration</h2>
    @using (Html.BeginForm("SignUp", "User", FormMethod.Post, new { id = "signupform", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FullAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FullAddress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FullAddress, "", new { @class = "text-danger" })
                </div>
            </div>

            @*-----------------------DROP DOWN ALERT-------------------------*@
            <div class="form-group">
                <label class="control-label col-md-2"></label>
                <div class="col-md-10">
                    <div id="countrydiv">
                        @Html.DropDownList("CountryList", (IEnumerable<SelectListItem>)ViewBag.CountryList, "- Country -", new { @class = "form-control text-center", style = "Float: Left" })
                    </div>
                    <div id="citydiv">

                    </div>
                </div>
            </div>
            @*------------------------------------------------*@

            <div class="form-group">
                <label class="control-label col-md-2">Upload Image</label>
                <div class="col-md-10">
                    <input type="file" id="profilePic" name="profilePic" value="" />
                    @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="date" name="BirthDate" value="" class="form-control" />
                    @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3">@Html.RadioButton("Gender", "Male", new { @checked = true }) Male </label>
                <label class="control-label col-md-3">@Html.RadioButton("Gender", "Female") Female </label>
                @*@Html.LabelFor(model => model.Female, htmlAttributes: new {@class = "control-label col-md-3"})
                    <div class="col-md-1">
                        <div class="checkbox pull-right">
                            @Html.RadioButton("Gender", "Female")
                            @Html.ValidationMessageFor(model => model.Female, "", new {@class = "text-danger"})
                        </div>
                    </div>*@
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Sign Up" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

@section myScript{
    <script type="text/javascript">

        var ddlcountry = document.getElementById("CountryList");
        ddlcountry.addEventListener("change",
            () => {
                var countryId = ddlcountry.selectedIndex;
                var url = "/User/CityLists/" + countryId;

                fetch(url).then((response) => {
                    return response.text();
                }).then((data) => {
                    const el = document.getElementById("citydiv");
                    el.innerHTML = data;
                });
            });

        $("#profilePic").click(function () {
            alert(" Please Upload 4:3 PORTRAIT image!");
        });

    </script>

}

BookPakistanTour/Views/User/UserDelete.cshtml
@model BookPakistanTourClasslibrary.UserManagement.User

@{
    ViewBag.Title = @Model.FullName + " Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 class="list-group-item-heading text-center notextselect">User Managment</h3>

<h3>Are you sure you want to delete this User?</h3>
<div class="col-lg-9">
    <h4>Delete User @Model.FullName</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Male)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Male)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Female)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Female)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "UserManagment")
        </div>
    }
</div>

BookPakistanTour/Views/User/UserDetails.cshtml
@model BookPakistanTourClasslibrary.UserManagement.User

@{
    ViewBag.Title = @Model.FullName + " Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 class="list-group-item-heading text-center notextselect">User Managment</h3>

<div class="col-lg-9">
    <h4>User Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullAddress)
        </dd>

        <dt>
            Location
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.Name), @Html.DisplayFor(model => model.City.Country.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Male)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Male)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Female)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Female)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd>

            <img src="@Url.Content(Model.ImageUrl)" alt="userimage" style="height:85px; width:70px" />

        </dd>
    </dl>
    <p>
        @Html.ActionLink("Edit", "UserEdit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "UserManagment")
    </p>
</div>

BookPakistanTour/Views/User/UserManagment.cshtml
@model IEnumerable<BookPakistanTourClasslibrary.UserManagement.User>

@{
    ViewBag.Title = "UserManagment";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 class="list-group-item-heading text-center notextselect">User Managment</h3>

<div class="col-lg-9">
    <h4>List Of Registered Users</h4>
    @if (ViewBag.message != null)
    {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Error!</strong> @ViewBag.message
        </div>
    }
    <table id="datatable" class="table table-condensed table-striped table-bordered table-hover display compact">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FullName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Role)
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Role.Name)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.Phone)
                        </td>*@
                    <td class="text-center">
                        @Html.ActionLink("Edit", "UserEdit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "UserDetails", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "UserDelete", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <br />
</div>