BookPakistanTour/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookPakistanTourClasslibrary;
using BookPakistanTourClasslibrary.BookingManagment;
using BookPakistanTourClasslibrary.TourManagement;
using BookPakistanTourClasslibrary.UserManagement;

namespace BookPakistanTour.Controllers
{
    public class BookingController : Controller
    {
        private readonly DbContextClass db = new DbContextClass();
        // GET: Booking
        public ActionResult BookTrip(int id)
        {
            User user = (User)Session[WebUtil.CURRENT_USER];
            if (user == null)
            {
                return RedirectToAction("Login", "User");
            }

            Tour tour = new TourHandler().GetTourById(id);
            ViewBag.HideSlider = true;
            return View(tour);
        }

        public ActionResult BookingConfirmed(int id)
        {
            User user = (User)Session[WebUtil.CURRENT_USER];
            if (user == null)
            {
                return RedirectToAction("Login", "User");
            }
            Tour tour = new TourHandler().GetTourById(id);

            Booking booking = new Booking
            {
                Tour = tour,
                UserId = user.Id
            };

            new BookingHandler().AddBooking(booking);
            ViewBag.HideSlider = true;
            return View();
        }

        public ActionResult BookingList()
        {
            List<Booking> bookings = new BookingHandler().GetAllBookings();
            return View(bookings);
        }

        public ActionResult Delete(int? id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Booking booking = new BookingHandler().GetBookingById(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: History/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Booking booking = new BookingHandler().GetBookingById(id);
            db.Entry(booking.Tour).State = EntityState.Unchanged;
            db.Entry(booking.User).State = EntityState.Unchanged;
            db.Entry(booking).State = EntityState.Deleted;
            db.Bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("BookingList");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public int GetBokingCount()
        {
            return (new BookingHandler().BookingCount());
        }
    }
}

BookPakistanTour/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookPakistanTourClasslibrary;
using BookPakistanTourClasslibrary.CompanyManagement;
using BookPakistanTourClasslibrary.LocationManagement;
using BookPakistanTourClasslibrary.UserManagement;
using FYProject1.Models;

namespace BookPakistanTour.Controllers
{
    public class CompanyController : Controller
    {
        // GET: Company
        public ActionResult CompanyManagment()
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Home", act = "Index" });
            }
            List<Company> companies = new CompanyHandler().GetAllCompanies();

            ViewBag.message = TempData["message"];

            return View(companies);
        }

        // GET: Company/Details/
        public ActionResult CompanyDetails(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Company company = new CompanyHandler().GetCompanybyId(id);
            return View(company);
        }

        // GET: Company/Create
        public ActionResult AddCompany()
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            LocationHandler lh = new LocationHandler();
            ViewBag.CountryList = ModelHelper.ToSelectItemList(lh.GetCountries());
            return View();
        }

        // POST: Company/Create
        [HttpPost]
        public ActionResult AddCompany(FormCollection fdata)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            try
            {
                Company c = new Company
                {
                    Name = fdata["Name"],
                    Description = fdata["Description"],
                    FacebookPageUrl = fdata["FacebookPageUrl"],
                    City = new City { Id = Convert.ToInt32(fdata["CityList"]) }
                };
                long numb = DateTime.Now.Ticks;
                int count = 0;
                foreach (string fname in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[fname];
                    if (!string.IsNullOrEmpty(file?.FileName))
                    {
                        string url = "/ImagesData/CompanyImages/" + numb + "_" + ++count + file.FileName.Substring(file.FileName.LastIndexOf(".", StringComparison.Ordinal));
                        string path = Request.MapPath(url);
                        file.SaveAs(path);
                        c.ImageUrl = url;
                    }
                    else
                    {
                        string url = "/ImagesData/CompanyImages/noimage2.jpg";
                        c.ImageUrl = url;
                    }
                }
                new CompanyHandler().AddCompany(c);
                return RedirectToAction("CompanyManagment");
            }
            catch
            {
                return View();
            }
        }

        // GET: Company/Edit/
        public ActionResult EditCompany(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Company company = new CompanyHandler().GetCompanybyId(id);
            return View(company);
        }

        // POST: Company/Edit/5
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult EditCompany(Company company)
        {
            try
            {
                User u = (User)Session[WebUtil.CURRENT_USER];
                if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
                {
                    return RedirectToAction("Login", "User", new { ctl = "Home", act = "Index" });
                }

                if (ModelState.IsValid)
                {
                    new CompanyHandler().UpdateCompany(company);
                    return RedirectToAction("CompanyManagment");
                }
                return View(company);
            }
            catch
            {
                return View();
            }
        }

        // GET: Company/Delete/5
        public ActionResult DeleteCompany(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Company company = new CompanyHandler().GetCompanybyId(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Company/Delete/5
        [HttpPost, ActionName("DeleteCompany")]
        public ActionResult DeleteCompanyConfirmed(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            try
            {
                Company company = new CompanyHandler().GetCompanybyId(id);
                new CompanyHandler().DeleteCompany(company);
                return RedirectToAction("CompanyManagment");
            }
            catch
            {
                ViewBag.message = "Cannot Delete. This Company Is Assigned To Some Tour. Delete That Tour First";
                TempData["message"] = ViewBag.message;
                return RedirectToAction("CompanyManagment");
            }
        }

        public int GetCompanyCount()
        {
            return new CompanyHandler().GetCompanyCount();
        }
    }
}

BookPakistanTour/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;

using System.Web;
using System.Web.Mvc;
using BookPakistanTourClasslibrary;
using BookPakistanTourClasslibrary.CompanyManagement;
using BookPakistanTourClasslibrary.TourManagement;
using BookPakistanTourClasslibrary.UserManagement;
using FYProject1.Models;

namespace BookPakistanTour.Controllers
{
    public class TourController : Controller
    {
        // GET: Tour
        public ActionResult TourManagment()
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Home", act = "Index" });
            }
            List<Tour> tours = new TourHandler().GetAllTours();
            ViewBag.message = TempData["message"];
            return View(tours);
        }

        public ActionResult TourDetails(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Tour tour = new TourHandler().GetTourById(id);
            return View(tour);
        }

        [HttpGet]
        public ActionResult AddTour()
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            ViewBag.companies = ModelHelper.ToSelectItemList(new CompanyHandler().GetAllCompanies());
            return View();
        }

        [HttpPost]
        public ActionResult AddTour(FormCollection fdata)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Product", act = "AddProduct" });
            }
            try
            {
                Tour t = new Tour
                {
                    Title = fdata["Title"],
                    Description = fdata["Description"], //.Replace(" ", "&nbsp;").Replace("\n", "<br>"),
                    Price = Convert.ToSingle(fdata["Price"]),
                    Sale = Convert.ToSingle(fdata["Sale"]),
                    Company = new Company { Id = Convert.ToInt32(fdata["CompanyList"]) },
                    DepartureDate = fdata["DepartureDate"]
                };
                long numb = DateTime.Now.Ticks;
                int count = 0;

                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase file = Request.Files[i];
                    if (file != null && file.ContentLength > 0)
                    {
                        string name = file.FileName;
                        string url = "/ImagesData/TourImages/" + numb + "_" + ++count +
                                     file.FileName.Substring(file.FileName.LastIndexOf("."));
                        string path = Request.MapPath(url);
                        file.SaveAs(path);
                        t.TourImages.Add(new TourImages() { Caption = name, ImageUrl = url });
                    }
                    else
                    {
                        string name = "No Image";
                        string url = "/ImagesData/TourImages/noimage2.jpg";
                        t.TourImages.Add(new TourImages { Caption = name, ImageUrl = url });
                    }
                }

                new TourHandler().AddTour(t);
                return RedirectToAction("TourManagment");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult EditTour(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Tour tour = new TourHandler().GetTourById(id);
            ViewBag.companies = ModelHelper.ToSelectItemList(new CompanyHandler().GetAllCompanies());
            return View(tour);
        }

        // POST: Company/Edit/5
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult EditTour([Bind(Include = "Id,Title,Description,Price,Sale,DepartureDate")]Tour tour)
        {
            try
            {
                User u = (User)Session[WebUtil.CURRENT_USER];
                if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
                {
                    return RedirectToAction("Login", "User", new { ctl = "Home", act = "Index" });
                }

                if (ModelState.IsValid)
                {
                    new TourHandler().UpdateTour(tour);
                    return RedirectToAction("TourManagment");
                }
                return View(tour);
            }
            catch
            {
                return View();
            }
        }

        public ActionResult DeleteTour(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Tour tour = new TourHandler().GetTourById(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        // POST: Tour/Delete/
        [HttpPost, ActionName("DeleteTour")]
        public ActionResult DeleteTourConfirmed(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            try
            {
                Tour tour = new TourHandler().GetTourById(id);
                new TourHandler().DeleteTour(tour);


                return RedirectToAction("TourManagment");
            }
            catch
            {
                ViewBag.message = "Cannot Delete. This Tour Is Assigned To Some Booking. Delete That Booking First";
                TempData["message"] = ViewBag.message;
                return RedirectToAction("TourManagment");
            }
        }

        public int GetTourCount()
        {
            return new TourHandler().GetTourCount();
        }
    }
}

BookPakistanTour/Views/Booking/BookTrip.cshtml
@using BookPakistanTourClasslibrary
@using BookPakistanTourClasslibrary.UserManagement
@model BookPakistanTourClasslibrary.TourManagement.Tour

@{
    ViewBag.Title = "BookTrip";
    Layout = "~/Views/Shared/_Layout.cshtml";
    User currentUser = (User)Session[WebUtil.CURRENT_USER];
}

<h2>Tour Booking</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd style="color:">
            @if (Model.Description.Length > 200)
            {
                @Model.Description.Substring(0, 200)
            }
            else
            {
                @Html.DisplayFor(model => model.Description)
            }
            . . . .<br />
            <a href="@Url.Action("TourDetail","Home", new { id = Model.Id})">Read More</a>
        </dd>

        <dt>
            Travel Company
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd style="font-weight: bold">
            @Html.DisplayFor(model => model.Price)/- Only - Per Person
        </dd>

        <dt>
            Discount
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sale)%
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureDate) <p class="text-danger" style="font-size: smaller">Please ReConfirm Timings On Call</p>
        </dd>

        <dt>
            Final Price
        </dt>
        <dd style="font-size: 1.2em; font-weight: bold">
            @if (Model.Sale != 0 || Model.Sale != null)
            {
                @($"{Model.Price - (Model.Price * Model.Sale / 100):N0}")
            }
            else
            {
                @Model.Price
            }
            /- Per Person
        </dd>
    </dl>
</div>
<a href="@Url.Action("TourDetail","Home", new { id = Model.Id})">Revisit Tour</a>
<hr />
<h4>Booking By:</h4>
<dl class="dl-horizontal">
    <dt>Name</dt>
    <dd>@currentUser.FullName</dd>
    <dt>Phone</dt>
    <dd>@currentUser.Phone</dd>
    <dt>Email</dt>
    <dd>@currentUser.Email</dd>
    <dd><a href="@Url.Action("UserGuestUpdate","User", new {id = currentUser.Id})">Update Your Details</a></dd>
</dl>
<hr />
<div class="text-center text-danger">Please Make Sure Before Clicking Confirm Booking!</div>
<a class="btn btn-primary btn-block" href="@Url.Action("BookingConfirmed", "Booking", new {id = Model.Id})">Confirm Booking</a>

BookPakistanTour/Views/Booking/BookingConfirmed.cshtml
@{
    ViewBag.Title = "Booking Confirmed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h1>Booking Confirmed!</h1>
    <p>Thank You!  We Will Contact You By Email And Call To Confirm Your Trip Booking</p>
    <a class="btn btn-success" href="@Url.Action("Index","Home")">Home</a>
</div>

BookPakistanTour/Views/Booking/BookingList.cshtml
@model IEnumerable<BookPakistanTourClasslibrary.BookingManagment.Booking>

@{
    ViewBag.Title = "BookingList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-9">
    <h2>BookingList</h2>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tour)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tour.Company)
            </th>

            <th>Actions</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.FullName)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Tour.Title)*@
                    <a href="@Url.Action("TourDetails","Tour", new { id = item.Tour.Id})">@item.Tour.Title</a>
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Tour.Company.Name)*@
                    <a href="@Url.Action("CompanyDetails","Company", new { id = item.Tour.Company.Id})">@item.Tour.Company.Name</a>
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</div>

BookPakistanTour/Views/Booking/Delete.cshtml
@model BookPakistanTourClasslibrary.BookingManagment.Booking

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-9">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Booking</h4>
        <hr />
        <dl class="dl-horizontal">

            @Model.User.FullName
            <br />
            @Model.Tour.Title
            <br />
            @Model.Tour.Company.Name
            <br />

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "BookingList")
            </div>
        }
    </div>
</div>